spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
server:
  port: 8081
