spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 5
    virtual-host: chat

